drone:
  type: "mavlink"
  connection_string: "tcp:127.0.0.1:5760"

simulation:
  mode: true

takeoff:
  altitude: 1.6

land:
  mode: "LAND"

camera:
  down_source: "ros"
  #front_source : "c920"
  down_ros_topic: "/down_camera"
  #id : 6

image: 
  width: 640
  height: 640